- name: Download Neovim AppImage
  get_url: 
    url: https://github.com/neovim/neovim/releases/download/v0.3.1/nvim.appimage
    dest: /tmp/nvim.appimage
    mode: 0744

- name: Install Neovim from AppImage
  command: /tmp/nvim.appimage
  become: yes

- name: Remove default configuration
  file: path=/home/vagrant/.config/nvim/init.vim state=absent

- name: Copy main configuration file
  copy: src=init.vim dest=/home/vagrant/.config/nvim/

- name: Set vim as git editor
  git_config: name=core.editor scope=global value=nvim
